image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  DOCKER_DRIVER: overlay2

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -U -e .
  - pip install -U -e .[docs]
  - pip install -U -e .[test]

stages:
  - build
  - test
  - analyze
  - deploy

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - venv/
    - .sonar/cache

build:
  stage: build
  script:
    - pip install wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    name: tibia.py-dist
    paths:
      - dist/

sonarcloud-check:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner
  before_script: []
  dependencies:
    - coverage
  only:
    - merge_requests
    - master
    - dev

docs:
  stage: build
  script:
    - cd docs
    - make html
  artifacts:
    name: tibia.py-docs
    paths:
      - docs/_build/

coverage:
  stage: test
  script:
      - coverage run setup.py test
      - coverage report
      - coverage html
      - coverage xml
  artifacts:
    name: Coverage_Report
    paths:
      - htmlcov/
      - coverage.xml

pages:
  stage: deploy
  dependencies:
    - docs
    - coverage
  script:
    - mkdir public
    - mv htmlcov/ public/coverage/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
