image: python:3.6

before_script:
  - pip install -r requirements.txt

pages:
  script:
    - pip install Sphinx
    - cd docs
    - make html
    - cp -r _build ../public
  artifacts:
    paths:
      - public