image: python:3.6

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

before_script:
  - pip install -U -e .
  - pip install -U setuptools wheel

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    name: tibia.py-dist
    paths:
      - dist/

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  stage: build
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - dev

docs:
  stage: build
  script:
    - pip install -U -e .[docs]
    - cd docs
    - make html
  artifacts:
    name: tibia.py-docs
    paths:
      - docs/_build/

coverage:
  stage: test
  script:
      - pip install coverage
      - pip install -U -e .[test]
      - coverage run setup.py test
      - coverage report
      - coverage html
  artifacts:
    name: Coverage_Report
    paths:
      - htmlcov/

pages:
  stage: deploy
  dependencies:
    - docs
    - coverage
  script:
    - mkdir public
    - mv htmlcov/ public/coverage/
    - mv docs/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
