language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

git:
  depth: 3

install:
  - pip install -U -r requirements.txt
  - pip install -U setuptools
  - pip install -U Sphinx

script:
  - python setup.py sdist
  - cd docs
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/_build/html
  keep-history: true
  on:
      branch: master
      python: "3.6"