language: python

python:
  - "3.6"

cache: pip

git:
  depth: 3

install:
  - pip install -U -r requirements.txt
  - pip install -U setuptools
  - pip install -U Sphinx
  - cd docs
  - make html

script:
  - python setup.py sdist

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/_build/html
  keep-history: true
  on:
      branch: master