language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

git:
  depth: 3

install:
  - pip install -U -r requirements.txt
  - pip install -U setuptools

script:
  - python setup.py sdist